
const list = [
  {
    id: 1,
    Avalible: "10",
    title: "Bags",
    price: 500,
    fav: false,
    rating: 2,
    discount: 0,
    category: "Bags",
   
    img: "https://m.media-amazon.com/images/I/71hYpRG8KLL._UX679_.jpg",
    img1: "https://m.media-amazon.com/images/I/81e95xfx4uL._UX679_.jpg",
    img2: "https://m.media-amazon.com/images/I/61l761KmtGL._UX679_.jpg",
    content:
      " Backpacks for Girls Boys Trending Backpack  Laptop Bag (SkyBlue)",
    amount: 0,
  },

  {
    id: 2,
    Avalible: "10",
    title: "iphone xs",
    price: 100000,
    fav: false,
    rating: 3,
    discount: 0,
    category: "Mobiles",
    content: "Apple iPhone 13 (128GB) - Blue",
    img: "https://m.media-amazon.com/images/I/71hATRruXVL._SX679_.jpg",
    img1: "https://m.media-amazon.com/images/I/71xhB9znTzL._SX679_.jpg",
    img2: "https://m.media-amazon.com/images/I/71M4v6FAAiL._SX679_.jpg",
    amount: 0,
  },

  {
    id: 3,
    Avalible: "10",
    title: " Rolex watches",
    price: 200000,
    fav:  false,
    rating: 4,
    discount: 0,
    category: "watches",
    content: "Redux Analog Linear Designer Dial Men’s & Boy's Watch",
    img: "https://m.media-amazon.com/images/I/714AbUmKhoS._UX679_.jpg",
    img1: "https://m.media-amazon.com/images/I/71CPsqiP9TS._UX679_.jpg",
    img2: "https://m.media-amazon.com/images/I/71HHXeNB-bL._UX679_.jpg",
    amount: 0,
  },
  {
    id: 4,
    Avalible: "10",
    title: "Nike Shoes",
    price: 5000,
    fav:  false,
    rating: 3,
    discount: 0,
    category: "Shoes",
    content: "WORLD WEAR FOOTWEAR Men Red-1243 Sports Shoes",
    img: "https://m.media-amazon.com/images/I/71IIn-p3WSL._UX695_.jpg",
    img1: "https://m.media-amazon.com/images/I/71hq15kF1hL._UX695_.jpg",
    img2: "https://m.media-amazon.com/images/I/71hq15kF1hL._UX695_.jpg",
    amount: 0,
  },
  {
    id: 5,
    title: "Laptops",
    Avalible: "10",
    price: 89000,
    fav:  false,
    rating: 4,
    discount: 0,
    category: "Laptops",
    content:
      "HP 15s,11th Gen Intel Core /Intel UHD Graphics/Dual Speakers/1.69 Kg",
    img: "https://m.media-amazon.com/images/I/414057taYKL._SX300_SY300_QL70_FMwebp_.jpg",
    img1: "https://m.media-amazon.com/images/I/71U9lLS9uPL._SX679_.jpg",
    img2: "https://m.media-amazon.com/images/I/71uqmN2b2UL._SX679_.jpg",
    amount: 0,
  },
  {
    id: 6,
    Avalible: "10",
    title: " bata Shoes",
    price: 5000,
    fav: false,
    rating: 5,
    discount: 0,
    category: "Shoes",
    content: "WORLD WEAR FOOTWEAR Men Red-1243 Sports Shoes",
    img: "https://m.media-amazon.com/images/I/7156HUlSOmL._UX695_.jpg",
    img1: "https://m.media-amazon.com/images/I/81NexeMBjAL._UX695_.jpg",
    img2: "https://m.media-amazon.com/images/I/71Xo0eJJb4L._UX695_.jpg",
    amount: 0,
  },

  {
    id: 7,
    title: " hp Laptops",
    Avalible: "10",
    price: 69000,
    fav:  false,
    rating: 4,
    discount: 0,
    category: "Laptops",
    content:
      "HP 15s,11th Gen Intel Core /Intel UHD Graphics/Dual Speakers/1.69 Kg",
    img: "https://m.media-amazon.com/images/I/41ZziloHwRL._SX300_SY300_QL70_FMwebp_.jpg",
    img1: "https://m.media-amazon.com/images/I/717kn3qCRVL._SX679_.jpg",
    img2: "https://m.media-amazon.com/images/I/71-kS6tzpAL._SX679_.jpg",
    amount: 0,
  },

  {
    id: 8,
    Avalible: "10",
    title: "SkyBags",
    price: 1500,
    fav:  false,
    rating: 2,
    discount: 0,
    category: "Bags",
    img: "https://m.media-amazon.com/images/I/71oJhR5IV8L._UX679_.jpg",
    img1: "https://m.media-amazon.com/images/I/71Zfw6IvaiL._UX679_.jpg",
    img2: "https://m.media-amazon.com/images/I/71ovxQq0y1L._UX679_.jpg",
    content:
      " Backpacks for Girls Boys Trending Backpack  Laptop Bag (SkyBlue)",
    amount: 0,
  },

  {
    id: 9,
    Avalible: "10",
    title: "Watches",
    price: 2000,
    fav:  false,
    rating: 4,
    discount: 0,
    category: "watches",
    content: "Redux Analog Linear Designer Dial Men’s & Boy's Watch",
    img: "https://m.media-amazon.com/images/I/51yJ6Iua3oL._UY679_.jpg",
    img1: "https://m.media-amazon.com/images/I/61f6Ji7qOWL._UY679_.jpg",
    img2: "https://m.media-amazon.com/images/I/511iu56lzTL._UY679_.jpg",
    amount: 0,
  },
  {
    id: 10,
    Avalible: "10",
    title: "iphone",
    price: 150000,
    fav:  false,
    rating: 2,
    discount: 0,
    category: "Mobiles",
    content: "Apple iPhone 13 (128GB) - Blue",
    img: "https://m.media-amazon.com/images/I/314Rp+8XKWL._SX342_SY445_.jpg",
    img1: "https://m.media-amazon.com/images/I/61NTwRtdzfL._SX679_.jpg",
    img2: "https://m.media-amazon.com/images/I/71OxEU5mSCL._SX679_.jpg",
    amount: 0,
  },
  {
    id: 11,
    Avalible: "10",
    title: "jewellery",
    price: 250000,
    fav:  false,
    rating: 5,
    discount: 0,
    category: "jewellery",
    content:
      "Mixed Metal; Colour: Gold; Occasion: Festive; Stone Type : Pearl; Stone Color: Pink & Green; Product Dimensions: 32 CM X 5 CM X 0.2 CM;",
    img: "https://m.media-amazon.com/images/I/6114nKyrk2L._UY695_.jpg",
    img1: "https://m.media-amazon.com/images/I/610ZaxuI7hL._UY695_.jpg",
    img2: "https://m.media-amazon.com/images/I/61wDagAjpWL._UY695_.jpg",
    amount: 0,
  },



  {
    id: 12,
    Avalible: "10",
    title: "iphone",
    price: 170000,
    fav:  false,
    rating: 4,
    discount: 0,
    category: "Mobiles",
    content: "Apple iPhone 13 (128GB) - red",
    img: "https://m.media-amazon.com/images/I/71gm8v4uPBL._AC_UY327_FMwebp_QL65_.jpg",
    img1: "https://m.media-amazon.com/images/I/61Yc75iMUWL._SX679_.jpg",
    img2: "https://m.media-amazon.com/images/I/81edi2EvglL._SX679_.jpg",
    amount: 0,
  },
  {
    id: 13,
    Avalible: "10",
    title: "iphone ",
    price: 150000,
    fav:  false,
    rating: 2,
    discount: 0,
    category: "Mobiles",
    content: "Apple iPhone 13 (128GB) - Pink",
    img: "https://m.media-amazon.com/images/I/31p5cVyRLmL._SY445_SX342_QL70_FMwebp_.jpg",
    img1: "https://m.media-amazon.com/images/I/61NTwRtdzfL._SX679_.jpg",
    img2: "https://m.media-amazon.com/images/I/71OxEU5mSCL._SX679_.jpg",
    amount: 0,
  },
  {
    id: 14,
    Avalible: "10",
    title: "Watches",
    price: 2000,
    fav:  false,
    rating: 4,
    discount: 0,
    category: "watches",
    content: "Redux Analog Linear Designer Dial Men’s & Boy's Watch",
    img: "https://m.media-amazon.com/images/I/71EnJ6+CCBS._UX679_.jpg",
    img1: "https://m.media-amazon.com/images/I/61f6Ji7qOWL._UY679_.jpg",
    img2: "https://m.media-amazon.com/images/I/511iu56lzTL._UY679_.jpg",
    amount: 0,
  },
  
  {
    id: 15,
    Avalible: "10",
    title: "Watches",
    price: 2000,
    fav:  false,
    rating: 4,
    discount: 0,
    category: "watches",
    content: "Redux Analog Linear Designer Dial Men’s & Boy's Watch",
    img: "https://m.media-amazon.com/images/I/51yJ6Iua3oL._UY679_.jpg",
    img1: "https://m.media-amazon.com/images/I/61f6Ji7qOWL._UY679_.jpg",
    img2: "https://m.media-amazon.com/images/I/511iu56lzTL._UY679_.jpg",
    amount: 0,
  },
  {
    id: 16,
    Avalible: "10",
    title: "iphone",
    price: 170000,
    fav:  false,
    rating: 4,
    discount: 0,
    category: "Mobiles",
    content: "Apple iPhone 13 (128GB) - red",
    img: "https://m.media-amazon.com/images/I/71gm8v4uPBL._AC_UY327_FMwebp_QL65_.jpg",
    img1: "https://m.media-amazon.com/images/I/61Yc75iMUWL._SX679_.jpg",
    img2: "https://m.media-amazon.com/images/I/81edi2EvglL._SX679_.jpg",
    amount: 0,
  },
  
  
];

export default list;
